#!/usr/bin/env python3
"""Regenerate the option tables that can be derived from the code itself.

docs/PARAMETERS.md documents the C++ modem. The two layers above it had no equivalent,
so 'what can I actually pass?' had no complete answer for ./run.sh or for LoRa. Both are
generated here from the source of truth — run_algo's parser and the LoRa driver's own
signature — so they cannot drift the way a hand-written list would.

    python3 docs/make_parameters.py          # rewrite docs/PARAMETERS_ALGO.md
"""
import inspect
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "union"))
sys.path.insert(0, os.path.join(REPO, "drivers", "lora", "python"))

OUT = os.path.join(REPO, "docs", "PARAMETERS_ALGO.md")


def run_sh_table():
    import run_algo
    ap = run_algo.build_parser()
    rows = []
    for a in ap._actions:
        if not a.option_strings or a.dest == "help":
            continue
        names = ", ".join(f"`{o}`" for o in a.option_strings)
        default = "" if a.default in (None, False) else f"`{a.default}`"
        choices = (" — one of " + ", ".join(f"`{c}`" for c in a.choices)) if a.choices else ""
        # A pipe inside help text would split the markdown row it lives in.
        helptext = " ".join((a.help or "").split()).replace("|", "\\|")
        rows.append(f"| {names} | {helptext}{choices} | {default} |")
    return rows


def lora_table():
    import lora_driver
    sig = inspect.signature(lora_driver.LoRaChannel.__init__)
    rows = []
    for name, p in sig.parameters.items():
        if name == "self":
            continue
        default = "" if p.default is inspect._empty else f"`{p.default}`"
        rows.append(f"| `{name}` | {default} |")
    return rows


def main():
    run_rows, lora_rows = run_sh_table(), lora_table()
    body = f"""# All options above the modem

Generated by `docs/make_parameters.py` from the code itself — do not edit by hand.
The C++ modem's own ~100 options are in [`PARAMETERS.md`](PARAMETERS.md); anything not
named below is still reachable with `--usrp-set KEY=VALUE` / `--lora-set KEY=VALUE`.

## `./run.sh` — {len(run_rows)} options

| Flag | Meaning | Default |
|---|---|---|
""" + "\n".join(run_rows) + f"""

## LoRa driver variables — {len(lora_rows)}

Set any of these with `--lora-set NAME=VALUE`. The named `--lora-*` flags above cover the
common ones; this is the complete surface, taken from `LoRaChannel.__init__`.

| Variable | Default |
|---|---|
""" + "\n".join(lora_rows) + "\n"
    with open(OUT, "w") as f:
        f.write(body)
    print(f"wrote {os.path.relpath(OUT, REPO)}: {len(run_rows)} run.sh options, "
          f"{len(lora_rows)} LoRa variables")
    return 0


if __name__ == "__main__":
    sys.exit(main())
